Ensure all command line flags are passed on in start-dev command
Also ensuring simpler password policy in dev env

diff --git a/devspace.yaml b/devspace.yaml
--- a/devspace.yaml
+++ b/devspace.yaml
@@ -71,19 +71,6 @@ vars:
   DEVSPACE_ENV_FILE: ".devspace/.env"
 
 pipelines:
-  # Main entrypoint for development (`devspace dev`). This starts all server components
-  # and the nodes. Make sure that you have run `devspace run-pipeline init` before.
-  dev:
-    run: |-
-      if ! command -v uname >/dev/null 2>&1; then
-        echo "--------------------------------"
-        echo "Error: This script must be run in a Unix-like shell (Bash/sh)."
-        echo "Windows OS is not supported! Please use WSL2 if you are on Windows."
-        echo "--------------------------------"
-        exit 1
-      fi
-      dev/start.sh ${POPULATE_MARKER}
-
   populate:
     run: |-
       python dev/populate.py \
@@ -211,6 +198,9 @@ deployments:
           keycloakConfigCli:
             configuration:
               realm:
+                # overwrite password policy - we don't need to enforce a password policy
+                # for dev environment
+                passwordPolicy: ""
                 # Overwrite users: for dev environment, initialize admin user fully and
                 # turn off MFA, so we don't need to configure OTP and setup account on
                 # first login.
@@ -223,7 +213,9 @@ deployments:
                     lastName: Admin
                     credentials:
                       - type: password
-                        value: Admin123!
+                        # note that for the dev env, we also overwrite the password in
+                        # the values.yaml file (this pw is easier)
+                        value: admin
                   - username: service-account-backend-admin-client
                     enabled: true
                     serviceAccountClientId: backend-admin-client
@@ -490,7 +482,16 @@ commands:
   # for development.
   start-dev:
     description: "Start the development environment"
-    command: devspace dev
+    command: |
+      if ! command -v uname >/dev/null 2>&1; then
+        echo "--------------------------------"
+        echo "Error: This script must be run in a Unix-like shell (Bash/sh)."
+        echo "Windows OS is not supported! Please use WSL2 if you are on Windows."
+        echo "--------------------------------"
+        exit 1
+      fi
+      POPULATE=$(./dev/ask_populate_marker.sh $POPULATE_MARKER)
+      $(./dev/get_start_command.sh $POPULATE $POPULATE_MARKER "$@")
 
   # This will remove all running k8s resources from the development mode.
   stop-dev:
@@ -509,4 +510,4 @@ commands:
   rebuild:
     description: "Rebuild images for this project (use --server, --node, --store, --ui for specific images)"
     command: |
-      $(./dev/get_rebuild_command.sh "$@")
+      echo $(./dev/get_rebuild_command.sh "$@")
